### PR TITLE
feat(Connection): send feature flag on connect

### PR DESCRIPTION
**Pull request by GuillaumeSalles**
Send feature flag header on connect to keep them inside the falcor session. 

Will be used in this PR : https://github.com/Mixgenius/LANDR.Falcor/pull/233

Did I miss something?

### CODE REVIEW

**Comment by ardeois** [comment]
@GuillaumeSalles Falcor-HTTP-WS-DataSource is a public project that ideally should be agnostic from implementation.
I'm not sure adding feature flags here make sense. We should maybe add a hook mechanism or a way to enhance the authorization payload?

**Comment by GuillaumeSalles** [comment]
screen shot 2017-09-26 at 4 43 12 pm

**Comment by GuillaumeSalles** [comment]
Is it really used?

**Comment by ardeois** [comment]
No it's not used because we use a private fork I wanted to remove (see closed PR https://github.com/Mixgenius/Falcor-HTTP-WS-DataSource/pull/1)

I am ok if we are aware this project will/can not be used by external community anymore

**Review by ludovicthomas — APPROVED** [review]
We will improve it later with a hook if there is a need for others to use it. The authorization with bearerToken is also not conventional if somebody wants to use something else.

In all cases, it's not a breaking change, as if there is no header, it will just return null and do nothing.

**Comment by GuillaumeSalles** [comment]
I just bumped the version. I suppose only @synhaptein can push the new version to npm?

**Comment by GuillaumeSalles** [comment]
Published

**Pull request merged**
